import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API='http://localhost:8080';
function Login({onLogin}){const [u,setU]=useState('admin'),[p,setP]=useState('admin123'),[e,setE]=useState(''); async function submit(ev){ev.preventDefault();setE('');try{const r=await fetch(API+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});if(!r.ok)throw new Error(await r.text());onLogin(await r.json())}catch(x){setE(x.message)}} return <div className="login"><form onSubmit={submit}><h1>Market Data</h1><p>OKX market data proxy</p><input value={u} onChange={e=>setU(e.target.value)} placeholder="Username"/><input value={p} onChange={e=>setP(e.target.value)} type="password" placeholder="Password"/><button>Sign in</button>{e&&<div className="error">{e}</div>}<small>Demo: admin / admin123</small></form></div>}
function App({auth,onLogout}){const [view,setView]=useState('markets'),[markets,setMarkets]=useState([]),[selected,setSelected]=useState('BTC-USDT'),[book,setBook]=useState({bids:[],asks:[]}),ws=useRef(null);
 useEffect(()=>{let live=true;async function load(){try{const r=await fetch(API+'/api/markets/top20');if(r.ok&&live)setMarkets(await r.json())}catch{}}load();const id=setInterval(load,5000);return()=>{live=false;clearInterval(id)}},[]);
 useEffect(()=>{if(view!=='book')return; if(ws.current)ws.current.close();const s=new WebSocket(`ws://localhost:8080/ws/market?token=${encodeURIComponent(auth.token)}`);ws.current=s;s.onopen=()=>s.send(JSON.stringify({op:'subscribe',instId:selected}));s.onmessage=e=>{try{const x=JSON.parse(e.data);if(x.type==='session_replaced'){alert('This session was replaced by another login.');onLogout();return}if(x.arg?.channel==='books'&&x.data?.[0])setBook({bids:x.data[0].bids||[],asks:x.data[0].asks||[]})}catch{}};return()=>s.close()},[selected,view]);
 function logout(){fetch(API+'/api/auth/logout',{method:'POST',headers:{'X-Session-Token':auth.token}}).finally(onLogout)}
 return <div><header><b>Market Data Service</b><nav><button className={view==='markets'?'active':''} onClick={()=>setView('markets')}>Market Overview</button><button className={view==='book'?'active':''} onClick={()=>setView('book')}>Order Book</button><button onClick={logout}>Logout</button></nav></header>{view==='markets'?<main><h2>Top 20 Spot Pairs</h2><table><thead><tr><th>Symbol</th><th>Last Price</th><th>24h Change</th><th>24h Volume (quote)</th><th></th></tr></thead><tbody>{markets.map(m=><tr key={m.symbol}><td><b>{m.symbol}</b></td><td>{m.lastPrice}</td><td className={Number(m.change24hPercent)>=0?'up':'down'}>{m.change24hPercent}%</td><td>{Number(m.volume24h).toLocaleString(undefined,{maximumFractionDigits:2})}</td><td><button onClick={()=>{setSelected(m.symbol);setView('book')}}>Order book</button></td></tr>)}</tbody></table></main>:<main><div className="toolbar"><h2>Order Book — {selected}</h2><select value={selected} onChange={e=>setSelected(e.target.value)}>{markets.map(m=><option key={m.symbol}>{m.symbol}</option>)}</select></div><div className="books"><Book title="Bids" rows={book.bids} side="bid"/><Book title="Asks" rows={book.asks} side="ask"/></div></main>}</div>}
function Book({title,rows,side}){return <section><h3>{title}</h3><table><thead><tr><th>Price</th><th>Size</th><th>Orders</th></tr></thead><tbody>{rows.slice(0,15).map((r,i)=><tr key={i}><td className={side}>{r[0]}</td><td>{r[1]}</td><td>{r[3]||'-'}</td></tr>)}</tbody></table></section>}
function Root(){const [auth,setAuth]=useState(null);return auth?<App auth={auth} onLogout={()=>setAuth(null)}/>:<Login onLogin={setAuth}/>};createRoot(document.getElementById('root')).render(<Root/>);
